name: Deploy to EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ~/web-backend

            git stash
            git pull origin develop

            ./gradlew build -x test

            docker network inspect web-network >/dev/null 2>&1 || docker network create web-network

            docker rm -f one-website-backend || true
            docker-compose down || true

            export SPRING_PROFILES_ACTIVE=prod

            docker-compose build --no-cache
            docker-compose up -d
