name: Deploy to EC2

on:
  push:
    branches: [ main ]  # main 브랜치에 코드가 올라오면 실행!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            # 1. 백엔드 폴더로 이동
            cd ~/web-backend/web_backend

            # 2. 최신 코드 가져오기
            git pull origin main

            # 3. 빌드 (테스트는 시간 걸리니 일단 제외)
            ./gradlew build -x test

            # 네트워크가 없으면 생성하는 명령어 추가
            docker network inspect web-network >/dev/null 2>&1 || docker network create web-network

            # 4. 컨테이너 새로 띄우기 (이미 빌드된 JAR를 포함해서 다시 빌드)
            docker-compose up -d --build
